### PR TITLE
Fix unicast sending to itself + console send support

### LINKED ISSUE #417: Subscribe ConsoleService to unicast message with `console` protocol_id

### PR DESCRIPTION
**Pull request by echupriyanov**
* Handle case of unicast messgaes to self
* Subscribe console to unicast messages
  * subscribe to unicast stream with protocol id = `console`
  * display received messages

Closes #417, #418

### CODE REVIEW

File: src/console.rs [hunk 1]
```diff
@@ -457,6 +463,18 @@ impl Future for ConsoleService {
             }
         }
 
+        loop {
+            // Process unicast messages
+            match self.unicast_rx.poll() {
+                Ok(Async::Ready(Some(msg))) => {
+                    info!("Received unicast message. From: {}, Data: {}", msg.from, String::from_utf8_lossy(&msg.data));
```
Comment (rtsisyk) [inline src/console.rs]: I use the following convention for messages:

Message text: arg1=xxx, arg2=xxx
